import { Success } from "@/typings";

export const success: Success = {
  ESTABLISHMENT_CREATION_SUCCESS: {
    title: "ESTABLISHMENT_CREATION_SUCCESS_TITLE",
    description: "ESTABLISHMENT_CREATION_SUCCESS_DESCRIPTION",
    text: "VIEW_ESTABLISHMENTS_BUTTON_TITLE"
  },

  SERVICE_CREATION_SUCCESS: {
    title: "SERVICE_CREATION_SUCCESS_TITLE",
    description: "SERVICE_CREATION_SUCCESS_DESCRIPTION",
    text: "VIEW_SERVICES_BUTTON_TITLE"
  },

  EMPLOYEE_CREATION_SUCCESS: {
    title: "EMPLOYEE_CREATION_SUCCESS_TITLE",
    description: "EMPLOYEE_CREATION_SUCCESS_DESCRIPTION",
    text: "VIEW_EMPLOYEES_BUTTON_TITLE"
  },

  EMAIL_VERIFICATION_SUCCESS: {
    title: "EMAIL_VERIFICATION_SUCCESS_TITLE",
    description: "EMAIL_VERIFICATION_SUCCESS_DESCRIPTION",
    text: "EMAIL_VERIFICATION_SUCCESS_BUTTON_TITLE"
  },

  EMAIL_VERIFICATION_RENEW_SUCCESS: {
    title: "EMAIL_VERIFICATION_RENEW_SUCCESS_TITLE",
    description: "EMAIL_VERIFICATION_RENEW_SUCCESS_DESCRIPTION",
  },
};
